-- MySQL Script generated by MySQL Workbench
-- Thu Jan 21 14:20:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nama_depan` VARCHAR(45) NOT NULL,
  `nama_belakang` VARCHAR(45) NOT NULL,
  `jenis_kelamin` VARCHAR(45) NOT NULL,
  `tempat_lahir` VARCHAR(45) NOT NULL,
  `tanggal_lahir` DATE NOT NULL,
  `alamat` LONGTEXT NOT NULL,
  `telp` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wali_Orang_Tua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Wali_Orang_Tua` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Wali_Orang_Tua` (
  `status_wali` VARCHAR(45) NOT NULL,
  `pekerjaan` VARCHAR(45) NOT NULL,
  `User_username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`User_username`),
  CONSTRAINT `fk_Wali_Orang_Tua_User`
    FOREIGN KEY (`User_username`)
    REFERENCES `mydb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perkuliahan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Perkuliahan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Perkuliahan` (
  `id` INT NOT NULL,
  `ruangan` VARCHAR(45) NOT NULL,
  `hari` VARCHAR(45) NOT NULL,
  `jam` TIME NOT NULL,
  `kode_prs` VARCHAR(45) NOT NULL,
  `tahun_ajar` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_perwalian_idx` (`kode_prs` ASC, `tahun_ajar` ASC),
  INDEX `fk_perwalian` (`tahun_ajar` ASC, `kode_prs` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Program_Studi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Program_Studi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Program_Studi` (
  `kode_prodi` INT(5) NOT NULL,
  `nama_prodi` VARCHAR(45) NOT NULL,
  `Fakultas_kode_fakultas` VARCHAR(255) NOT NULL,
  `Dosen_nid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`kode_prodi`),
  INDEX `fk_Program_Studi_Fakultas1_idx` (`Fakultas_kode_fakultas` ASC),
  INDEX `fk_Program_Studi_Dosen1_idx` (`Dosen_nid` ASC),
  CONSTRAINT `fk_Program_Studi_Fakultas1`
    FOREIGN KEY (`Fakultas_kode_fakultas`)
    REFERENCES `mydb`.`Fakultas` (`kode_fakultas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Program_Studi_Dosen1`
    FOREIGN KEY (`Dosen_nid`)
    REFERENCES `mydb`.`Dosen` (`nid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dosen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dosen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dosen` (
  `nid` VARCHAR(45) NOT NULL,
  `jabatan_fungsional` VARCHAR(45) NOT NULL,
  `tahun_masuk` INT NOT NULL,
  `User_username` VARCHAR(255) NOT NULL,
  `Perkuliahan_id` INT NOT NULL,
  `terdaftar` INT(5) NOT NULL,
  PRIMARY KEY (`nid`, `User_username`),
  INDEX `fk_Dosen_User1_idx` (`User_username` ASC),
  INDEX `fk_Dosen_Perkuliahan1_idx` (`Perkuliahan_id` ASC),
  INDEX `fk_Dosen_Program_Studi1_idx` (`terdaftar` ASC),
  CONSTRAINT `fk_Dosen_User1`
    FOREIGN KEY (`User_username`)
    REFERENCES `mydb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dosen_Perkuliahan1`
    FOREIGN KEY (`Perkuliahan_id`)
    REFERENCES `mydb`.`Perkuliahan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dosen_Program_Studi1`
    FOREIGN KEY (`terdaftar`)
    REFERENCES `mydb`.`Program_Studi` (`kode_prodi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fakultas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fakultas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fakultas` (
  `kode_fakultas` VARCHAR(255) NOT NULL,
  `nama_fakultas` VARCHAR(45) NOT NULL,
  `Dosen_nid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`kode_fakultas`),
  INDEX `fk_Fakultas_Dosen1_idx` (`Dosen_nid` ASC),
  CONSTRAINT `fk_Fakultas_Dosen1`
    FOREIGN KEY (`Dosen_nid`)
    REFERENCES `mydb`.`Dosen` (`nid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perwalian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Perwalian` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Perwalian` (
  `kode_prs` VARCHAR(45) NOT NULL,
  `semester` INT NOT NULL,
  `tahun_ajar` VARCHAR(45) NOT NULL,
  `jumlah_sks` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `tanggal_diajukan` VARCHAR(45) NOT NULL,
  `tanggal_disetujui` VARCHAR(45) NOT NULL,
  `Dosen_nid` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`kode_prs`),
  INDEX `fk_Perwalian_Dosen1_idx` (`Dosen_nid` ASC),
  INDEX `fk_index` (`tahun_ajar` ASC),
  CONSTRAINT `fk_Perwalian_Dosen1`
    FOREIGN KEY (`Dosen_nid`)
    REFERENCES `mydb`.`Dosen` (`nid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mata_Kuliah`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mata_Kuliah` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mata_Kuliah` (
  `kode_mata_kuliah` VARCHAR(45) NOT NULL,
  `nama_mata_kuliah` VARCHAR(45) NOT NULL,
  `SKS` INT NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  `kurikulum` VARCHAR(45) NOT NULL,
  `Perkuliahan_id` INT NOT NULL,
  PRIMARY KEY (`kode_mata_kuliah`),
  INDEX `fk_Mata_Kuliah_Perkuliahan1_idx` (`Perkuliahan_id` ASC),
  CONSTRAINT `fk_Mata_Kuliah_Perkuliahan1`
    FOREIGN KEY (`Perkuliahan_id`)
    REFERENCES `mydb`.`Perkuliahan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mahasiswa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mahasiswa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mahasiswa` (
  `nim` VARCHAR(45) NULL,
  `status_masuk` VARCHAR(45) NULL,
  `User_username` VARCHAR(255) NOT NULL,
  `Wali_Orang_Tua_User_username` VARCHAR(255) NOT NULL,
  `Program_Studi_kode_prodi` INT(5) NOT NULL,
  `Dosen_nid` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`nim`, `User_username`),
  INDEX `fk_Mahasiswa_User1_idx` (`User_username` ASC),
  INDEX `fk_Mahasiswa_Wali_Orang_Tua1_idx` (`Wali_Orang_Tua_User_username` ASC),
  INDEX `fk_Mahasiswa_Program_Studi1_idx` (`Program_Studi_kode_prodi` ASC),
  INDEX `fk_Mahasiswa_Dosen1_idx` (`Dosen_nid` ASC),
  CONSTRAINT `fk_Mahasiswa_User1`
    FOREIGN KEY (`User_username`)
    REFERENCES `mydb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mahasiswa_Wali_Orang_Tua1`
    FOREIGN KEY (`Wali_Orang_Tua_User_username`)
    REFERENCES `mydb`.`Wali_Orang_Tua` (`User_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mahasiswa_Program_Studi1`
    FOREIGN KEY (`Program_Studi_kode_prodi`)
    REFERENCES `mydb`.`Program_Studi` (`kode_prodi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mahasiswa_Dosen1`
    FOREIGN KEY (`Dosen_nid`)
    REFERENCES `mydb`.`Dosen` (`nid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
